branches:  
  only:
    - master
services:  
#Enable docker service inside travis
  - docker
before_install:  
  
script: 
  - docker --version  # document the version travis is using
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
after_script:
  #build the image
  - docker build --no-cache -t $DOCKER_IMAGE_NAME .
  # tag the build as latest
  - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:latest 
  # push  both images
  - docker push $DOCKER_IMAGE_NAME:latest
env:
  - $DOCKER_IMAGE_NAME="3blades/logspout"
notifications:
  slack: 3blades:3blades:XahVulsT3BSOlFzGmoXHiKDi